version: "3"

services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "5000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sharecipe
    volumes:
      - mysqldata:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: sharecipe
      MONGO_INITDB_ROOT_PASSWORD: sharecipe
    volumes:
      - mongodata:/data/db

volumes:
  mysqldata: {}
  mongodata: {}
