version: "3"

services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sharecipe-dev
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
