FROM amazoncorretto:21

ENV TZ=UTC

WORKDIR authub

COPY . .

RUN ./mvnw clean package -DskipTests

EXPOSE 8888

CMD ["java", "-Xmx250m", "-Dspring.profiles.active=qa", "-jar", "./target/authub-1.0.0.jar"]