version: "3"

services:
  authub:
    build:
      context: .
      dockerfile: Dockerfile.dev
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M
    env_file:
      - dev.jvm.conf