FROM amazoncorretto:21

ENV TZ=UTC

WORKDIR authub

COPY . .

RUN ./mvnw test -Punit-tests

RUN ./mvnw clean package -DskipTests

EXPOSE 8001

CMD ["java", "-Dspring.profiles.active=dev", "-jar", "./target/authub-0.0.1.jar"]