version: "3"

services:
  gourmetdiscovery:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M
    env_file:
      - dev.jvm.conf
