server:
  port: 3333
spring:
  profiles:
    active: dev
  application:
    name: taste-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: ${frontend.url}
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: authub
          uri: lb://authub
          predicates:
            - Path=/authub/actuator/**
        - id: authub
          uri: lb://authub
          predicates:
            - Path=/api/v1/chefs/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}-${random.uuid}